apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgBTzmEWtV5chH3n8SHDuxX6jxJIa40tTPHr8gOzSeNP4OJBft4J1uT8gSFth2MWy8js44T80YYkMqEVlc3rnfWHjgNaZbtqMtfNS1mwK+MI5jgPMM63FPzRmOVjelZ2BSVsQaTEJROn4zqKxgKVXuZq+UXfw+c5qCF1dJzGbVzOnmlgVg6LvzYZ2U6XNlRQ4AQAR38UTsgWidyMoZRrhEExOZR0NAckHwT1MBdVaVde0G3rUCNFQzy3piQ10sK7ldqiD0A6Ve68gVMHSLo1zOy6VhBa5dBJUlN39y8I9igK0NYtITf8aNz/Brypd7Os7zkr0jxqDRSNyb4AFsBcLu0tqrwTR8S3AFeMvo1Ie29kn1Bs6ld2yqE+mAWkgrAjF+ByiPuu790U6JS6aeVHZFmkajBLRTbkfZRjFjuXC5hbe8WeJZ8uCekiypkd2Rt02UoPfUxIAkBRdsb1xuLQkk6qyMMZ5jFRmzOwHM7BFMBS0YKC5aNv5pHFI44Iuu4bYUCf5nkiRSm7Hw5YnZBQUP8/CcCa+heEK35brWbIaxa4VOxFnwQxKUgVRQIZZXCToEvqMDYq8Vetf/r4MnqDVE2ceo3zLoq7abguptprNTAFmdukZorwepzJz6NU/iXoG1FN9anUB+Rz5Q6nOkTtcdL5tflOKwHe0195kX++Rt82Bin4KNOFOx1ZzLAsSgCYUl6UWypH2XAXxZJmTkkY5XPxFoO+Y8nju1s8
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

